### ISSUE TITLE
Rebuild new Pjsip 2.12.1

### ISSUE THREAD

**Issue by TechGuyVN** [VoIPGRID/Vialer-pjsip-iOS#55]
### Version

3.5
### File / Feature

Rebuild lib with newest PJSIP 2.12.1

### Expected behaviour

import to project Success

### Actual behaviour
i modify vialerbuild and add config i want:
    echo "#define PJ_CONFIG_IPHONE 1" >> $PJSIP_CONFIG_SITE_H
    echo "#define PJ_IPHONE_OS_HAS_MULTITASKING_SUPPORT 1" >> $PJSIP_CONFIG_SITE_H
    echo "#define PJ_ACTIVESOCK_TCP_IPHONE_OS_BG 0" >> $PJSIP_CONFIG_SITE_H
    echo "#define PJ_HAS_TCP 1" >> $PJSIP_CONFIG_SITE_H
    echo "#define PJMEDIA_VIDEO_DEV_HAS_FFMPEG  1" >> $PJSIP_CONFIG_SITE_H
Update version pjsip to 2.12.1

I try to rebuild with this command:
./vialerbuild  --enable-ipv6 --opus -h264

Everything ok, framework created successful 

Import VialerPJSIP.framework to our project error (i try copy& replace folder, try to create pod too) it throw error: 
`/Pods/Vialer-pjsip-iOS/VialerPJSIP.framework/Headers/pj/compat/limits.h:31:12: error build: 'VialerPJSIP/limits.h' file not found`

I have tried to config many times but not working, i see limits.h still there and structure framework same with 3.5 version of this project on Gis.

pls help

### Stacktrace / Error message

{paste here}

### Other info

{anything else that might be related/useful}

**Comment by IdoElkaim** [comment]
I’m getting the same error when trying to compile with version 2.12.1.

I just wanted to ask, have you tried compiling it again with 2.10?

I am currently stuck trying to compile it for the new sdk but I’m getting an error  (171060 which means openssl is disabled even though I compiled with ssl).

**Comment by TechGuyVN** [comment]
@IdoElkaim ido
 i able to build 2.10 with no error, im using Macbook pro 2021 Macos Monterey 12.6

**Comment by IdoElkaim** [comment]
Can you please share your compiled framework? I’m trying to recompile ever since the new xcode came out but was not successful in getting a working version

**Comment by IdoElkaim** [comment]
> @IdoElkaim ido i able to build 2.10 with no error, im using Macbook pro 2021 Macos Monterey 12.6

I'll be happy to get some guidance if you got some time, or your compiled framework, Thank you.
